### ISSUE TITLE
Cannot configure password

### ISSUE THREAD

**Issue by Unitech** [pm2-hive/pm2-mysql#4]
Tried to install pm2-mysql and configured the password but still does not manage to connect to db

(https://app.keymetrics.io/#/bucket/560d52711b9e20a011379e93/dashboard)

(And I dont undestrand why the configured password is not replace by "password hidden")

**Comment by alavit-d** [comment]
Changed module build on npm, test with latest version (0.0.5)

**Comment by Unitech** [comment]
It still does not work with the latest version (https://app.keymetrics.io/#/bucket/560d52711b9e20a011379e93/dashboard), any clue on this?

**Comment by gohackfelipe** [comment]
Where can i configure this module?

**Comment by alavit-d** [comment]
Fixed on https://github.com/pm2-hive/pm2-mysql/commit/4a741033722b6a430707a5d1ce432bb7e9fcc53a

To configure the module refer to the [readme](https://github.com/pm2-hive/pm2-mysql#how-to-set-these-values-) or check out the Keymetrics dashboard
